### ISSUE TITLE
Hull classification of 海防艦 = PF

### ISSUE THREAD

**Issue by Tsubakura** [poooi/poi#1448]
Hello everyone, its Tsubakura of the wikia here.

After a very long debate in deciding whether to use DE or PF, we have obtained [proof](http://archive.hnsa.org/doc/id/oni222j-japan-navy/pg107.htm) that the 海防艦 should be classified as PF. The document is a reference manual of the USN in 1945, so I can assure you that it's accurate.

On a side note, I have seen that you guys have used the term DDE instead. DDE refers to full fledged destroyers that were refitted after the war for ASW purposes. The Kaiboukan are not destroyers, so DDE classification makes no sense at all.

With this, I hope that we all get to the same wavelength so that there won't be any inconsistencies across each info sources.

Best regards,

Tsubakura

**Comment by KagamiChan** [comment]
Thank you for you timely information :)

**Comment by Tsubakura** [comment]
You're welcome :)

**Comment by KochiyaOcean** [comment]
Matsu-class Destroyer is the realDestroyerEscort so reserve DE for them is a good decision :-)

**Comment by c933103** [comment]
Actually, the current situation is that
https://github.com/poooi/poi-plugin-ezexped this plugin use DDE code
https://github.com/poooi/plugin-navy-staff while this plugin use DE code for Kaibokans

**Comment by Tsubakura** [comment]
An update on the situation, since there has been some interesting development from each side.
We have contacted the NHHC and they have provided us a statement that neither PF or DE are 100% correct. They also have provided us [this](http://www.combinedfleet.com/Kaibokan.htm) source, which lists them all as **Escorts**, which is also exactly the same in the ship cards.

They had suggested to use only E, but we know full well that only using E is pretty confusing. Hence why we decided to create a list of made up classifications which we let them pick through a [poll](http://www.strawpoll.me/12943149). Atm, the votes are favoring EE from the looks of it.

**Comment by Javran** [comment]
just noticed there's a mentioning of ez exped plugin - as it's developer I'm pretty sure `DDE` is not being used anywhere except `stypes.json`, which is just a data file, partial extracted from KC3Kai translation files back when none of stype `1` ships were implemented. I'm not expecting it to be correct out of the box, and I'm more than ready to accept a change once this is sorted.

@Tsubakura can we by any chance take a look at the NHHC's statement about neither using PF nor DE? after all I don't feel comfortable inventing a new hull classification for ships that have been existed in history.

**Comment by Tsubakura** [comment]
![image](https://cloud.githubusercontent.com/assets/20300876/25976590/4eb54180-36b6-11e7-86d6-f30e50e075db.png)
![image](https://cloud.githubusercontent.com/assets/20300876/25976621/698ef1f4-36b6-11e7-8846-8b31b86ed7ed.png)
As they didn't directly mail them, but asked directly through an acquaintance who works at NHHC, I would have to ask Totaku directly regarding this if you want more clarification. 🤔

**Comment by Javran** [comment]
@Tsubakura that's fine, I'm not in need of any formal proof this time xD, just getting some ideas about why would ppl favor one over others, btw if the discussion happened on some discord channel perhaps I can take a look at chatting log.

**Comment by c933103** [comment]
I does not recommend changing the cpde away from PF/DE just because of that
as the reason why people argue for the code at the beginning weren't
arguing for it is how USN called them although that do become the most
significant argument for it in later part of the debate; the argument on DE
and PF was that they're the western counterpart to what Japanese called
Kaibokan, and as only they use these kind of codes to address ship classes,
it was suggested by people to adopt thpse western code over onto Japanese
warships. People never called Japanese warships this way, but that's not
what being argued for, the argument was only abput what kind of code in
western world would be best suit for this class.

2017年5月12日 08:15 於 "Javran Cheng" <notifications@github.com> 寫道：

**Comment by KochiyaOcean** [comment]
@c933103 Modern ship classification is based on USN standard, notice that IJN even didn't have a clear classification of carriers (All IJN carriers are called 'Kuubo', including USN's carrier classifications like CV, CVL, CVE, .etc)

**Comment by Tsubakura** [comment]
This was brought up, because people will keep insisting that either DE or PF is correct, without letting up. By drawing a consensus here, which is **Escort**, both are correct and all the debate which has occurred till now would be instantly resolved.

**Comment by c933103** [comment]
@Tsuba I thought up till this point the consensus was both codes describe
the role of kaibokan except we need to pick one code out of the two?
While creating a new code might provide a chance to settle the conflict,
such approach would drive us further away from existing standard. Btw can
we get opinion from editors of kancollewiki.net about this?
@東風谷オーシャン The thing is that the NHHC reply quoted above proved the USN does
not actually applies its own classification code onto Kaibokans, and the
staff have made their personal recommendation regarding what would be a
suitable code to be assigned to those escort ships. As such I think it mean
the community could revert to using a code from what we believed to be
western equivalency to the ship class  instead of baking out mew code
ourselves.

2017年5月12日 14:50 於 "Tsubakura" <notifications@github.com> 寫道：

**Comment by c933103** [comment]
Also, people on 4chan seems inclined toward the usage of DE

**Comment by Tsubakura** [comment]
I would really never use the people of 4chan as a basis to deciding matters, especially since they don't really know anything about history. The goal here is to settle on matters regarding historical accuracy, while at the same providing a standard that everyone can use.

I intended to invite Javran over to our group chat, but I haven't had a reply of the invitation yet. So I'll just paste the arguments over here and let you guys decide on the matter.

**Arguments that the Kaiboukan should be DE (Destroyer Escort):**
- The community has already accepted it as the correct classification, without even bothering to look through the historical facts.
- They have the same role generally during the WW2, even though they lack all the armanents and specifications of an American Destroyer Escort.
- The US Army identification magazine used both DE and PF interchangeably: https://archive.org/details/USANJOR194405-nsia (Note: Magazine, thus most likely not official practice)
- The documents could all have been written by someone from the Royal Navy or they could've exchanged info with them, which does not prove that the USN themselves uses the classification PF themselves.
- Nobody cares about the Naval Treaties, so we shouldn't either.

**Arguments that the Kaiboukan should be PF (Patrol Frigate):**
- The ONI has classified the Shimushu-class as PF: http://archive.hnsa.org/doc/id/oni222j-japan-navy/pg107.htm
- Page 40 of the USN Technical Mission to Japan classified the Kaiboukan as PF: http://www.fischer-tropsch.org/primary_documents/gvt_reports/USNAVY/USNTMJ%20Reports/USNTMJ-200H-0602-0659%20Report%20S-03.pdf
- The IJN does not treat any ships with no torpedo capabilities as destroyers.
- The Republic of China's Navy classified these ships as PF when they obtained them post-war. Likewise, the American Destroyer Escorts were given a different classification, which means there are distinctions.
- In-game, they cannot effectively replace DDs in most of the expeditions and map branching rules. It is evidence enough that they are not treated as destroyers, as genuine destroyer escorts should be able to effectively replace them.
- DE are subject to the London Naval Treaty of 1930 if they have a displacement of over 2000 ton, any gun above 155cm, more than 4 guns above 76mm, the ability to launch torpedoes and the speed of 20 knots or above. The Shimushu however, is nowhere near 2000 ton, does not have any gun above 155cm, only has 3 guns above 76mm at most, no torpedo capabilities and has a speed of 19.7 knots. They are not a destroyer by London Naval Treaty definitions.
- The Kaiboukan were built with the purpose of settling fishing disputes between USSR and Japan, not for use as an escort in war.
- The Kaiboukan lacks the armanent to be as combat effective as the American Destroyer Escorts. While the lightweight part does fit the role of the USN DE, their capabilities dont.
- The US Army identification magazine used both DE and PF interchangeably: https://archive.org/details/USANJOR194405-nsia (Note: Magazine, thus most likely not official practice)


**Arguments that the Kaiboukan should be EE (Escort):**
- The in-game shipcards themselves literally state that they're Escorts. Not PF or DE, but Kaiboukan and Escort.
- NHHC has provided a statement that they are Escorts. They have also provided the following trusted source: http://www.combinedfleet.com/Kaibokan.htm
- Escort can basically mean PF, DE and Kaiboukan, pretty much resolving everything in the debate.
- Although the ONI has assigned the first 3 Kaiboukan classes as PF, the 4th one is actually assigned as DE: http://archive.hnsa.org/doc/id/oni222j-japan-navy/pg115.htm
- Nobody can claim that EE is wrong, because it literally means Escort. In case foreign escorts gets added, there will be no problems at all if it gets the same API as the Kaiboukan.


**Arguments that the Kaiboukan should be KB (Kaiboukan):**
- Is there even an explanation needed? The ships are given the tag 海防 in their cards, so why don't we just classify them KB? 

I have personally drawn a conclusion from all the info that we have gathered from the historians, so I let you guys decide on this matter.

**Comment by KagamiChan** [comment]
Very detailed information, impressive.

Personally I'll be OK with kancolle wikia staff's final decision because each choice is enough reasonable, although KB makes me feel most familiar as a kanji/character user, and I've decided to use 海防 as abbreviation in my recent code for non-English interface.

**Comment by destroyerescorts** [comment]
As listed in http://www.navweaps.com/index_tech/index_ships_list.php DE referred to the following: Destroyer Escort, Escort or "Ocean Escort." The ships in question are Escorts, so DE fits that.

To address the PF arguments above:

> The ONI has classified the Shimushu-class as PF: http://archive.hnsa.org/doc/id/oni222j-japan-navy/pg107.htm

It also used DE for other kaibokan ships: http://archive.hnsa.org/doc/id/oni222j-japan-navy/pg115.htm These were wartime intelligence reports to begin with, so they relied on incomplete information and they were made for people who were concerned with combat, not terminology.
> DE are subject to the London Naval Treaty of 1930 if they have a displacement of over 2000 ton, any gun above 155cm, more than 4 guns above 76mm, the ability to launch torpedoes and the speed of 20 knots or above. The Shimushu however, is nowhere near 2000 ton, does not have any gun above 155cm, only has 3 guns above 76mm at most, no torpedo capabilities and has a speed of 19.7 knots. They are not a destroyer by London Naval Treaty definitions.

USS Evarts DE-5 had a displacement of between 1140 long tons standard and 1450 t full load. You did not post DE specifications. You apparently posted something inspired by Article 8, which only says the treaty limits the numbers of ships that meet the requirements. You posted nonsense, since a 155cm gun is more than three times larger than Yamato's main guns. You said 155, not 15.5, and besides, the treaty defines ships with 15.5cm guns as cruisers, so trying to claim destroyers or destroyer escorts are required to have 15.5cm guns is nonsense. If you're copy/pasting from someone else, you were trolled. 

Furthermore, the claim was "are subject to." If something doesn't meet the requirements of the treaty's Article 8, that just means there's no limit on how many of them can be built. That has nothing to do with what counts as a destroyer or destroyer escort. Article 15 defines destroyers as surface vessels of war the standard displacement of which does not exceed 1850 tons, and with a gun not above 5.1-inch (130mm). It doesn't set any minimum.
> The IJN does not treat any ships with no torpedo capabilities as destroyers.
> In-game, they cannot effectively replace DDs in most of the expeditions and map branching rules. It is evidence enough that they are not treated as destroyers, as genuine destroyer escorts should be able to effectively replace them.

Destroyer escorts (DE) are not destroyers (DD). Destroyer escorts can't effectively replace destroyers, and the DDE designation exists for full-fledged destroyers performing escort duties.
>The Kaiboukan were built with the purpose of settling fishing disputes between USSR and Japan, not for use as an escort in war.

Not according to the site you linked to earlier, http://www.combinedfleet.com/Kaibokan.htm Provide some evidence for your claim.
>The SHIMUSHU class of escorts was ordered in 1937. They were capable of functioning either as escorts or minesweepers.
> By 1943, increasing losses of merchant shipping caused the IJN to reorder its priorities. Beginning in January 1944 over 30 modified Type B's, known as the UKURU-class, were laid down. The heavy toll exacted by American submarines on the Combined Fleet's East Indies oil supply further caused the IJN to lose some of its hubris, so in 1943 it was decided to design a simplified version of the Type B. 

> The Republic of China's Navy classified these ships as PF when they obtained them post-war. Likewise, the American Destroyer Escorts were given a different classification, which means there are distinctions.

According to wikipedia, type C and D Escorts , which were numbered by Japan rather than named, were classified PF, and US DE's were F, but Etorofu-class ships like Tsushima and Fukue didn't have classifications shown there and I haven't found anything with theirs yet. The list did have one mixing DD with PF: ROCN Xin Yang DD-15 (PF-82, ex IJN Hatsuume). Since there's inconsistencies, the ROCN wouldn't be a reliable source. It probably classified things based on how it was going to use them rather than just ship characteristics.

> The Kaiboukan lacks the armanent to be as combat effective as the American Destroyer Escorts. While the lightweight part does fit the role of the USN DE, their capabilities dont.

USS Evarts DE-5 armament, according to wikipedia (if you don't like wikipedia, link an alternative):
    3 × 3 in (76 mm)/50 cal dual purpose guns (3×1)
    4 × 1.1"/75 caliber anti-aircraft guns (1×4)
    9 × 20 mm (0.79 in) anti-aircraft cannons (9×1)
    8 × depth charge throwers
    1 × 24-tube Hedgehog anti-submarine spigot mortar (144 rounds)
    2 × depth charge tracks

Shimushu's armament:
    3 × 120 mm (4.7 in)/45 cal dual purpose guns
    Up to 15 × 25 mm (0.98 in) AA guns
    6 × depth charge throwers
    Up to 60 × depth charges
    1 × 80 mm (3.1 in) mortar
Shimushu had 120mm guns, while Evarts only had 76. Evarts only had 2 more depth charge throwers. They each had 3 main guns, similar numbers of anti-aircraft guns, one mortar, and that's it. These loadouts are as close to identical as you can get given the differences between the US and Japanese arsenals.

>Is there even an explanation needed? The ships are given the tag 海防 in their cards, so why don't we just classify them KB?

KB only makes sense to people who know the Japanese word. Anyone who isn't familiar with it or who tries to look it up in a historical list of classifications will need an explanation. And of course, EE and KB are just made up, not real designations.

**Comment by Tsubakura** [comment]
@destroyerescorts 

Glad that there's still so many history enthusiasts who are willing to participate in this debate. FYI, I have forwarded your points to [this thread](http://kancolle.wikia.com/wiki/Thread:558979) so I recommend that you should go there as well for the discussion.

**Comment by KagamiChan** [comment]
A clarification on the usage:
Any English name or abbreviation for kaiboukan is not shown on user-interface (`navy-staff` plugin has not been announced so only few alpha testers use it), so they have not propagated to our English users :)

**Comment by KagamiChan** [comment]
Seems the community chose `DE` at last
