### ISSUE TITLE
Can't set custom background without the blur filter

### ISSUE THREAD

**Issue by Kristjan-Zagar** [poooi/poi#1575]
I'm trying to set a custom background, but the image is barely visible and it's like there is a blur filter over it, how to remove that blur filter, so the image would be visible?

Thank you for the help in advance

**Comment by gnattu** [comment]
A short answer to your question is YES, but you may not like it as much as you think.

Click on the "Edit custom CSS" button you may see below the theme configuration, and add those lines with text editor opened to remove blur filters.

```css
div#custom-bg {
  filter: none !important;
}
```
-----
Longer version:
Even if you remove the blur filter, the image will not become as visible as you want because there is a translucent colored overlay on the image, which is the main reason of the invisibility. Such behavior is by design to make sure that you can see each and every element on the main poi as clearly as you should. A too bright and not blurred background would be distractive, and provide inadequate contrast, making the information on poi, which is more important than a fancy background, hard to identify. 

But you can also adjust the opacity of the overlay to the value you like.
Add these lines by editing custom css
```css
div#bg-overlay{
  background-color: rgba(42,42,42,0.9) !important;
}
```
Change the  last value of the `rgba` (which is 0.9 given is the sample)will change the opacity of the overlay. The maximum is 1,  which means totally opaque, and the minimum is 0,  which means totally transparent. 
----
Personal advice: Keep the filters and only change the opacity of the overlay if your background is visually complex, and never make the opacity lower than 0.5 unless your background is dark enough and will not block your sight.

**Comment by Kristjan-Zagar** [comment]
@gnattu Thank you very much for the reply, I've played with this in the developer options and it worked nicely.

But when I click the "Edit custom CSS" button, all I get opened is an **empty** .css file, is that what's suppose to happen?

![poi_2017-09-15_14-27-28](https://user-images.githubusercontent.com/22732730/30482123-201dbe4a-9a22-11e7-9074-8970400402fa.png)

**Comment by gnattu** [comment]
If you never used it before, it will create a new .css file which is empty.

**Comment by Kristjan-Zagar** [comment]
I've tried adding the lines you suggested into the custom css, but it seems that it did not overwrite the original settings. 

![poi_2017-09-15_14-48-20](https://user-images.githubusercontent.com/22732730/30482882-17842230-9a25-11e7-90f3-60caeb757246.png)

**Comment by KochiyaOcean** [comment]
@Kristjan-Zagar add `` !important`` before :;

**Comment by KochiyaOcean** [comment]
@Kristjan-Zagar Change theme or restart will apply changes

**Comment by Kristjan-Zagar** [comment]
Thank you very much for all the help and advice, it works now.
