### ISSUE TITLE
Help needed with AutoUpdate

### ISSUE THREAD

**Issue by Werseter** [poooi/poi#1971]
**poi 版本 / poi version:** 9.0.x

**操作系统 / OS:** Windows 8.1

**你遇到了什么样的问题 / The problem you've met:** Help needed with AutoUpdate

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** AutoUpdater downloads the update and prompts to quit app and install updates. Does any action have to be taken by a user to _actually_ install those updates? Just restarting or running `npm install` does not take any effect, I usually just tend to clone the reo

Console nor code don't seem to provide any insight, it might be either my misunderstanding of how AutoUpdate works, or something being done wrong on my side.

**Comment by KagamiChan** [comment]
the updater runs in background, it will first uninstall current version and then install the new. Since both tasks are time consuming, users often have to wait for several minutes until completed.

This feature is powered by `electron-builder` and we don't have much control on it. We have reports of upgrade failures but it is difficult to figure out the cause.

install prebuilt version and install from github repo are different, if you start from github repo, auto updater will not work

**Comment by Werseter** [comment]
Ah, I suppose that as I change some parts of the main view panel - the quests panel to be exact, to show the translated quest contents instead of untranslated quest name, I guess I have to stick to repo version and update manually. Thank you for quick reply.

**Comment by KagamiChan** [comment]
you're welcome

feel free to ask anything about poi development
