### ISSUE TITLE
Application clearing all cache on (system) crash

### ISSUE THREAD

**Issue by Werseter** [poooi/poi#2003]
**poi 版本 / poi version:**
9.0.3

**操作系统 / OS:**
Windows 8.1

**你遇到了什么样的问题 / The problem you've met:**
Application clearing all cache on (system) crash

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
Whenever it happens that my system crashes during when poi is running, after booting back up I have to cope with everything running quite painfully slowly (my connection speed is quite weak), due to the cache clearing it by itself. I was wondering if it is possible to somehow have the cache kept, and if it causes issues, have user use the Clear Cache option in the settings instead.

**Comment by KagamiChan** [comment]
The cache is managed by chromium side of Electron and we don't have much control on it, it is possible that the cache is corrupted due to system crashes if it is being written.

Poi does support custom cache for media resources and there's cache archives available (e.g. ShimakazeGo's), but this means that you have to update them manually after each server update

Currently we don't support "save media resource as custom cache" functionality because it is hard to tell when to use the cache and when to download new data, and such process will slow down the program
