### ISSUE TITLE
10.0.0 正式版，游戏画面未正常跟着游戏窗口缩放 

### ISSUE THREAD

**Issue by sandwichii** [poooi/poi#2063]
**poi 版本 / poi version:**
10.0.0正式版

**操作系统 / OS:**
Windows 7 x64 SP1

**你遇到了什么样的问题 / The problem you've met:**

更新后打开poi显示游戏画面后，游戏画面未正常按照窗口缩放，即使打开**设置固定分辨率**也没起到作用。

之前可以做到在“**显示设置**”中调节**游戏分辨率**时，游戏画面与游戏窗口**同步缩放**。

调节控制poi UI的**缩放滑竿**时发现游戏画面与poi UI同步缩放，但这个应该不是预期的效果。

**Comment by sandwichii** [comment]
![sp181230_170130](https://user-images.githubusercontent.com/8279800/50545881-89cbc900-0c58-11e9-8190-7ca2f3316c41.png)

**Comment by sandwichii** [comment]
@KochiyaOcean 只有一个没什么关系的报错
![sp181230_173132](https://user-images.githubusercontent.com/8279800/50547888-22c10b00-0c7e-11e9-8382-87ed61a2727e.png)

**Comment by sandwichii** [comment]
@KochiyaOcean 右键打开的是这个
![sp181230_215959](https://user-images.githubusercontent.com/8279800/50547906-69af0080-0c7e-11e9-80ca-b1a7b386558a.png)

**Comment by sandwichii** [comment]
@KochiyaOcean 岛风go

**Comment by sandwichii** [comment]
@KochiyaOcean 现在在这基础上出现了新的问题，重新打开poi之后游戏画面会恢复为原始尺寸，拖动缩放滑块依旧跟随着ui缩放且以当前画面为1乘百分比缩放，已经影响正常游戏了

**Comment by KochiyaOcean** [comment]
@sandwichii 岛风 Go 的那堆“优化”设置关掉看看？

**Comment by sandwichii** [comment]
@KochiyaOcean 岛风go1.8.2.2主界面上没看到优化开关

**Comment by KochiyaOcean** [comment]
在上面的 console 界面输入 `align()` 是否有报错

**Comment by ccen3020** [comment]
我用自己的SS也有这个问题
Uncaught ReferenceError: align is not defined
    at <anonymous>:1:1

**Comment by KochiyaOcean** [comment]
@ccen3020 确定是 webview 的开发者工具（右键打开，标题栏显示的是 DMM 的地址）吗

**Comment by ccen3020** [comment]
> @ccen3020 确定是 webview 的开发者工具（右键打开，标题栏显示的是 DMM 的地址）吗

原来左右键点还不一样……囧
右键点开之后，输入align()之后提示一个未定义，然后分辨率就切过去了，不过不会自己切换
align()
undefined
align()
undefined

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 只能说这不是预想中的情况，而且我们也没法重现这个 bug...

**Comment by NankyokuDenka** [comment]
> @NankyokuDenka 只能说这不是预想中的情况，而且我们也没法重现这个 bug...

如果说你们无法重现这个BUG的话是否意味着是更新导致的。如果把所有文件再清除是否能解决问题？游戏画面下方的「自动调整」也是无效的。但是有朋友就是有效的。她的应该是 win 版。

但是我不知道文件都放在哪里……还有数据希望能保留下来

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 目前看似乎都是岛风 Go 或者 ACGP 用户才会遇到这个问题，详细的情况不清楚（毕竟 chrome 内核也有更新，不好排除变量

**Comment by NankyokuDenka** [comment]
> @NankyokuDenka 目前看似乎都是岛风 Go 或者 ACGP 用户才会遇到这个问题，详细的情况不清楚（毕竟 chrome 内核也有更新，不好排除变量

我在日本。是直连的。不存在代理问题

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 你右击开发者工具按钮看看有没有报错？

**Comment by NankyokuDenka** [comment]
@KochiyaOcean 还真有。❌都是下面这个。ID我打码了不影响查BUG吧
<img width="787" alt="qq20181231-161002 2x" src="https://user-images.githubusercontent.com/27300519/50555956-90207a80-0d16-11e9-963a-08dba318fd9a.png">

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 右键的，不是左键

**Comment by NankyokuDenka** [comment]
@KochiyaOcean 右键的没有错误。只有⚠️，不过只是提示，和这个没关系。

**Comment by KochiyaOcean** [comment]
@NankyokuDenka console 输入 align() 回车是什么结果

**Comment by NankyokuDenka** [comment]
@KochiyaOcean undefined

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 能否适配

**Comment by NankyokuDenka** [comment]
@KochiyaOcean 没反应

**Comment by KochiyaOcean** [comment]
@NankyokuDenka window.ipc.access('WebView').width
的结果是？

**Comment by NankyokuDenka** [comment]
@KochiyaOcean 800。「游戏分辨率」哪里不管是百分之几这个指令的结果都是800

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 我之后调查一下...

**Comment by NankyokuDenka** [comment]
@KochiyaOcean 静候佳音

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 刚从有明回来，估计 2300 左右会有修复版本，到时候劳请测试

**Comment by NankyokuDenka** [comment]
@KochiyaOcean 辛苦了

**Comment by KochiyaOcean** [comment]
@NankyokuDenka https://poidb.0u0.moe/nightly/5873/poi-10.0.0-mac.zip 试试看这个版本？

**Comment by NankyokuDenka** [comment]
@KochiyaOcean 应用程序 “poi” 不能打开……

**Comment by KochiyaOcean** [comment]
@NankyokuDenka https://poidb.0u0.moe/nightly/5874/poi-10.0.0-mac.zip 这个呢

**Comment by NankyokuDenka** [comment]
@KochiyaOcean 还是不能打开。我确认一下，压缩包解压以后，是把里面的 poi.app 拖到「应用程序」里面没错吧。

**Comment by NankyokuDenka** [comment]
@KagamiChan 解压缩以后右键 poi.app 选择「打开」是吧？呃，还是提示不能打开。5873和5874都是这样

**Comment by KagamiChan** [comment]
@NankyokuDenka 
那你可能需要先更改 系统偏好 隐私与安全 里面的设置

![image](https://user-images.githubusercontent.com/3816900/50570210-18f0f200-0dbb-11e9-97ad-41527b6dea81.png)

**Comment by NankyokuDenka** [comment]
@KagamiChan
我之前也考虑过这个可能性，所以已经改成「」任何来源了。

**Comment by KagamiChan** [comment]
@NankyokuDenka 我这边 high sierra 没有发现有问题

**Comment by KagamiChan** [comment]
@NankyokuDenka 你下载 5879 看一下呢？
理论上这些版本和正版版不会有什么特殊变化

**Comment by NankyokuDenka** [comment]
@KagamiChan 还是这样

**Comment by NankyokuDenka** [comment]
@KagamiChan 我用这个 https://www.jianshu.com/p/179fafe83afb 提供的方法，发现确实macOS文件夹下不是可执行文件，执行命令之后可以打开，但是报错，提示
<img width="496" alt="2019-01-01 14 13 39" src="https://user-images.githubusercontent.com/27300519/50570457-83139200-0dcf-11e9-95c0-3a2413b361c2.png">

具体信息如下：
Process:               poi [797]
Path:                  /private/var/folders/*/poi.app/Contents/MacOS/poi
Identifier:            org.poooi.poi
Version:               10.0.0 (10.0.0.5879)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           poi [797]
User ID:               501

Date/Time:             2019-01-01 14:11:42.942 +0900
OS Version:            Mac OS X 10.14.2 (18C54)
Report Version:        12
Bridge OS Version:     3.2 (16P2542)
Anonymous UUID:        1F5693BD-9A13-72C1-2826-67585967E1F2


Time Awake Since Boot: 2900 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /private/var/folders/*/poi.app/Contents/MacOS/poi
  Reason: no suitable image found.  Did find:
	/private/var/folders/4d/wb48mp2j379fclfxw23tpshw0000gn/T/AppTranslocation/1C47FB03-33E0-42F1-8428-43CE89B7BDEC/d/poi.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/private/var/folders/4d/wb48mp2j379fclfxw23tpshw0000gn/T/AppTranslocation/1C47FB03-33E0-42F1-8428-43CE89B7BDEC/d/poi.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10c939000 -        0x10c939ffb +org.poooi.poi (10.0.0 - 10.0.0.5879) <0B17EBD3-270D-3C7F-A47F-A50793EC943D> /var/folders/*/poi.app/Contents/MacOS/poi
       0x110afe000 -        0x110b7ca67  dyld (640.2) <289AB27E-F09F-3384-A14A-100431139559> /usr/lib/dyld
    0x7fff3cf24000 -     0x7fff3cf24fff  com.apple.Cocoa (6.11 - 23) <D0BED932-C061-33E9-9F59-ECE0BA9F7EEB> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff3facc000 -     0x7fff3fe9afff  com.apple.Foundation (6.9 - 1561) <27FD022F-F0E3-3053-BADA-DF9BF856CA85> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff401c1000 -     0x7fff40253ff7  com.apple.framework.IOKit (2.0.2 - 1483.230.1) <AAAF13D1-80E5-3079-98C1-FA3C3FC47B40> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff491e1000 -     0x7fff49509fff  com.apple.security (7.0 - 58286.230.21) <5ADE179E-87D5-3B90-9172-D183D4665037> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff4998c000 -     0x7fff499fcff3  com.apple.SystemConfiguration (1.17 - 1.17) <A8FD596E-C858-397F-836C-978038B97AC0> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration

Model: MacBookPro15,2, BootROM 220.230.16.0.0 (iBridge: 16.16.2542.0.0,0), 4 processors, Intel Core i5, 2.3 GHz, 16 GB, SMC 
Graphics: Intel Iris Plus Graphics 655, Intel Iris Plus Graphics 655, Built-In
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, Samsung, K4EBE304EC-EGCG K4EBE304EC-EGCG
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, Samsung, K4EBE304EC-EGCG K4EBE304EC-EGCG
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Sep 18 2018 16:24:57 version 9.130.86.7.32.6.21 FWID 01-83a3fe91
Bluetooth: Version 6.0.9f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: iPhone, Ethernet, en7
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB Receiver
USB Device: iPhone
USB Device: iBridge Bus
USB Device: iBridge DFR brightness
USB Device: iBridge Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: iBridge ALS
USB Device: iBridge FaceTime HD Camera (Built-in)
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 34.6
Thunderbolt Bus: MacBook Pro, Apple Inc., 34.6

**Comment by KagamiChan** [comment]
确认目前的 nightly 没有办法在 mojave 上运行。但是因为和这个 issue 已经无关，所以单开了一个新 issue #2073

**Comment by NankyokuDenka** [comment]
@KagamiChan 悲报。只能等待你们更新了

**Comment by KagamiChan** [comment]
@NankyokuDenka https://poidb.0u0.moe/nightly/5884/
里面的 dmg 可以下载来试一下

**Comment by NankyokuDenka** [comment]
@KagamiChan 5884 这个版本可以自适应调整了。一开始还像原来那样无法调整。本来想切出来找上面那个代码，结果切回来就发现已经适配了。33%，67%，100%都能马上适配。

关掉之后重启，调整「固定分辨率」，一开始没有反应。大概等待约1分钟（掐秒表看了一次，1分14秒）才适配完成，之后再进行分辨率调整就能较快切换了。

重启的话会保持关闭之前的分辨率大小。

之前发布的正式版等待几分钟以后也没有能够适配。

**Comment by NankyokuDenka** [comment]
@KagamiChan 对了。还有另一件事有点不一样。截图的话，之前9.0.4，100%的分辨率，截图出来是2400x1440的图片，而之前不能改变大小（即67%）的那个10.0.0截图出来是1200x720，而现在5884这个版本100%大小截图出来的也是1200x720。这样子是符合你们设计的吗？

PS. 我的笔记本是2018版 13.3英寸的。默认的屏幕分辨率。

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 符合

**Comment by KochiyaOcean** [comment]
@NankyokuDenka 这边测试反应基本上还是比较快的……
