### ISSUE TITLE
Flash loading is not possible.

### ISSUE THREAD

**Issue by cul9** [poooi/poi#2114]
**poi 版本 / poi version:**
10.2.0
**操作系统 / OS:**  win10

 1803/ build 17134.523

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
Flash loading is not possible.
I have the same symptoms...
It's the same if i delete cookies,cache
Yesterday, it happened suddenly during the game
10.2.0
The same is true of reinstalling the program
I didn't install any other programs.
I was just surfing the Internet.

![cap 2019-02-10 08-03-24-934](https://user-images.githubusercontent.com/41810694/52527333-65104a00-2d0a-11e9-9d64-286c5333ff32.png)
![cap 2019-02-10 08-03-29-454](https://user-images.githubusercontent.com/41810694/52527334-680b3a80-2d0a-11e9-8770-b8b24aed6093.png)

**Comment by KagamiChan** [comment]
please try this nightly version and see if it helps: https://ci.appveyor.com/project/KochiyaOcean/poi/builds/22245469/artifacts

**Comment by pocari09** [comment]
I had same issues as well. Thank you for the support. @KagamiChan

**Comment by Kurikaeshi7** [comment]
Hello, I have the same problem, but I have found a way to continue playing. I also tried everything first to fix the same issue as clearing it with cache and cookies. I then tried it with the program SoftEther VPN and it works. The game loads as usual. When the game has finished loading, I turned off VPN and was able to continue playing.

I never used VPN to play the game before. Can it be that the problem is because of the IP address  why the game is not loading? Only weird that it happens now, because I play the game now for 2 weeks and since I could always play the game with Poi without problems and VPN.

Sorry for my worst English, hope it could help you all to find a solution to fix it.

**Comment by KagamiChan** [comment]
@Kurikaeshi7 The root cause is that the common area check bypass back's expiring time is fixed to a date that has just passed. With VPN you're bypassing the check via another way.

**Comment by Kurikaeshi7** [comment]
Ah okay. Thank you for your prompt reply.
how should that normally work without a VPN? What must be set in the setting for it to work?

**Comment by KagamiChan** [comment]
@Kurikaeshi7 we are preparing a new release. Before the next version is out you may try the provided nightly download link above

**Comment by cul9** [comment]
@KagamiChan 
Well solved thank you!
