### ISSUE TITLE
support ARM64.

### ISSUE THREAD

**Issue by ress997** [poooi/poi#2342]
PCs using ARM such as Surface, Apple M1 and some Chrome OS are becoming more common.

I would like to see each OS release an ARM64 version.

---
(我还会补充翻译成中文的文字。)

使用ARM的PC，如Surface、M1 Mac和一些Chrome OS正在变得越来越普遍。

所以我希望看到每个操作系统都能发布一个ARM64版本。

**Comment by KagamiChan** [comment]
Hi We're now waiting for the ARM support from our upstream dependencies. When everything is OK we'll start to publish ARM releases

but I have to say that because we don't have any ARM devices at hand, we cannot test or maintain these builds ourselves

**Comment by Takunsyo** [comment]
I don't know this will help or not, I'd like to provide my MacBook Pro (M1) for test.
I can't afford to sent it to you, but I can provide a remote connection for you to logon to my machine.

Hope this will help.
(I don't get to view GitHub so often, send a DM via twitter if interested. )

**Comment by ress997** [comment]
I think you can do some other inexpensive testing with Raspberry Pi.

By the way, I have a Raspberry Pi 4 and I think I can help you with your testing.

**Comment by KagamiChan** [comment]
Thanks for your offerings. Let's see how it will go


Even all these devices are ARM architecture, their OS are still different so we need to ship separately. And For Raspberry Pi I'm afraid it's not powerful enough for running HTML5 games

For Raspberry debian looks like the electron builder already has support, you may have a try: https://www.electron.build/cli.html#targetconfiguration

**Comment by gnattu** [comment]
In case you are interested, preliminary arm64 builds is available here: https://github.com/gnattu/poi/releases/tag/v10.6.0-arm64-alpha

Please be aware this is far from "official support", because our upstream is not working correctly on any targeted platform(Windows, Mac, Linux) at the moment and we have to manually patch upstream code to build on arm64, and some of the patches are dirty hacks. You can refer to the pull request linked to this issue for more details. 

The builds have been tested to run on these platforms using native arm64 processor:
- Windows 10 on ARM(7z and exe Installer)
- macOS 11 Big Sur(dmg and zip)
- Fedora 33(rpm and AppImage)

Other than "the build runs and loads", no other extensive tests have been done yet, so use it at your own risk.

**Comment by ress997** [comment]
@KagamiChan I was able to play 演習 on my Raspberry Pi 4 and Lenovo ideapad duet chromebook.

@Takunsyo You can try it on Mac.

@gnattu Failed to run on my Mac.

```
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
(electron) 'systemPreferences.isDarkMode()' is deprecated and will be removed. Please use 'nativeTheme.shouldUseDarkColors' instead.
```

**Comment by gnattu** [comment]
It can run on mine, what is the behavior of "fail to run"?

**Comment by gnattu** [comment]
@ress997 The release is updated now, you can try re-download and see if anything changes.

**Comment by KagamiChan** [comment]
FYI there're nightlies available at https://nightly.poi.moe/

the number corresponds to the azure pipeline build id

**Comment by gnattu** [comment]
Please note nightlies do not include arm64 builds yet.

**Comment by KagamiChan** [comment]
@gnattu Oh you may also add it, it just collects all the build artifacts and upload to the website

**Comment by ress997** [comment]
@gnattu I can try the new build and play the game with no problem!
@KagamiChan I've confirmed that I can play in my environment without any problems, so I'm looking forward to the new ARM version.

**Comment by ress997** [comment]
Mac version of `plugin[gpuinfo]` can show a window, but its contents are not displayed.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/48500247/102052972-588b3a00-3e2a-11eb-88ca-557e3d76a76b.png">

**Comment by gnattu** [comment]
> Mac version of `plugin[gpuinfo]` can show a window, but its contents are not displayed.

Not mac related, electron 11 does not handle `chrome://` urls any more, so this is expected at the moment.

**Comment by ress997** [comment]
> Not Mac related

I see, it was a problem with electron 11.

**Comment by gnattu** [comment]
The pull request is now in pre-final state and and ready for review. The blank GPU info mentioned in the issue is also fixed.
CI is now generating arm64 builds, starting build 5802 in https://nightly.poi.moe, the builds are arm64+x86_64 on all platforms.
Please note: these nightlies will not launch properly as they are lacking necessary fix from the master branch.  Useable nightlies will come after the PR is merged.

**Comment by Williamzhao700** [comment]
Hi all,
I've got the M1 MacBook and I'd love to help test. But when I try the "poi-10.6.0-arm64-mac.zip" in build 5802, it shows the warning that the application is broken even if I press control and click open. 

Is there anyway to avoid the security check? Thanks in advance.

**Comment by gnattu** [comment]
Because nightly build are not code signed, macOS will refuse to launch it.

Make sure you already dragged poi.app to Applications folder, then open a terminal, input:

```
xattr -d com.apple.quarantine /Applications/poi.app
```

Then press enter

You should be able to launch poi now.

**Comment by Williamzhao700** [comment]
It works, thanks a lot.
Really a significant boost in launch speed!

**Comment by ress997** [comment]
I cannot start it after updating it.
![image](https://user-images.githubusercontent.com/48500247/119302033-688f2b80-bc9e-11eb-8ce6-d0436d82a776.png)

**Comment by KagamiChan** [comment]
fxied
