### ISSUE TITLE
Will there be Rich Presence for Discord in poi?

### ISSUE THREAD

**Issue by Mattz-P** [poooi/poi#2389]
**poi 版本 / poi version:**

10.6.0

**操作系统 / OS:**

```
Device name	PC-XXXX
Processor	Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz
Installed RAM	64.0 GB (63.9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support
Edition	Windows 10 Pro
Version	20H2
Installed on	‎2021-‎03-‎31
OS build	19042.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0
```

**功能的详细描述 / Details on the feature:**

Will there be Rich Presence for Discord in poi? Some context: [Discord documentation](https://discord.com/developers/docs/rich-presence/how-to#so-what-is-it). 

Visualization: 
![image](https://user-images.githubusercontent.com/33806410/133316427-365d8ee3-ccb7-4b89-968a-ddf6dce2237e.png)

**Comment by Javran** [comment]
I don't see any official Discord SDK support for JS, however https://github.com/open-unlight/node-discord-game appears to provide exactly what we need. Probably an external plugin will do. I'll take a closer look but no promise for now.

**Comment by SSummer-UI** [comment]
I managed to made a demo version by simply pulling [poi-plugin-discord-rich-presence](https://github.com/SSummer-UI/poi-plugin-discord-rich-presence) in plugins folder under %AppData%\[roaming\]poi. I am, however, having problem publishing it on npm server which might be caused by . 

`
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/poi-plugin-discord-rich-presence - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
`

**Comment by SSummer-UI** [comment]
Demo image: 
![image](https://user-images.githubusercontent.com/72781410/134070019-89f1aa8e-0023-42ea-bf1f-e701ef4bb3e0.png)
