### ISSUE TITLE
Plz NOT to create shortcut for poi in Start Menu every time it runs

### ISSUE THREAD

**Issue by antitake** [poooi/poi#908]
Now there is a dozen of shortcuts named 'toast' created by poi in my Start Menu, and I have to clean it manually every time after poi runs. Can't find and items in Setting related to this 'feature'. Hope for some instruction about how to turn it off.

Cheers.

**Comment by yukixz** [comment]
Poi need a shortcut to send desktop notification. It's required by windows.

**Comment by KochiyaOcean** [comment]
See https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#windows

**Comment by JenningsWu** [comment]
So which version of poi are u using?

**Comment by antitake** [comment]
> See https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#windows

Looks like it's not necessary on Windows 10, maybe someone can add a check on system version?

> If the option to disable creating a shortcut is needed, I will add one.

I will really appreciate that.

**Comment by taroxd** [comment]
Although the notification works on Windows 10, removing the shortcut is not recommended for the following reasons.

1. Microsoft requires it.
2. Without the shortcut, you will no longer be able to configure notifications in Windows.
   That means, if you have disabled notification by mistake, you will not have the chance to re-enable it.
3. Why does this shortcut matter? Windows does this as well, for example, the `settings` app. If you do not want it, just ignore it. The lastest version use `poi` instead of `toast` so it does not seem so ugly.

We may provide the option. But I think it is better to keep the shortcut.
